# Generated by Django 5.2.4 on 2025-09-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmatch',
            name='matched_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='missing_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='recommended_resources',
            field=models.TextField(blank=True, null=True),
        ),
    ]
